Implement Date-reuploading classifier in Qiskit Machine Learning
qiskit-community/qiskit-machine-learning pull request #668
Opened 2023-07-12 16:01 UTC by ShivaniRajput11

### Description
Data re-uploading is a recently proposed idea of quantum neural network, which uses a quantum circuit with a series of data re-uploading and processing layers. Unlike the conventional quantum circuit of quantum neural network, it has multiple layers of re-uploading input data. In this project, we will implement the data re-uploading quantum neural network in Qiskit Machine Learning. The goal of this project is to write code and create a pull request

### Details and comments
The work is done in QAMP23 (https://github.com/qiskit-advocate/qamp-spring-23/issues/3)

2023-07-12 16:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-machine-learning?pullRequest=668) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-machine-learning?pullRequest=668) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-machine-learning?pullRequest=668) it.</sub>

2023-07-12 16:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-machine-learning?pullRequest=668) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-machine-learning?pullRequest=668) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-machine-learning?pullRequest=668) it.</sub>

2024-03-07 10:15 UTC, OkuyanBoga requested changes
The notebook needs to be updated for the unit tests:
* Check spelling
* Update outdated libraries

2024-06-11 20:01 UTC, edoaltamura commented
Hi @ShivaniRajput11, are you still interested in finishing this PR? There are just a few things left to change to make it compatible with the latest Qiskit ML version:
* update `from qiskit.utils import algorithm_globals`
* run the spellchecker and add unknown words to `.pylintdict`

2024-08-20 09:29 UTC, edoaltamura requested changes
Note the recent changes in Qiskit ML that would require changes in this PR:
- `from qiskit.utils import algorithm_globals`: `algorithm_globals` is now hosted in Qiskit ML directly since the merge of Qiskit Algorithm last week.
- A new tutorial, number 13, has been merged in the main branch, so this tutorial should be renamed with the number 14.
- The V1 primitives are being deprecated across the Qiskit ecosystem and this change may affect `SamplerQNN` used here. Soon we will update Qiskit ML to reflect this upgrade, so this tutorial may need to be adjusted as well.

2025-05-30 13:32 UTC, woodsp-ibm commented
Note: we ran into an issue on the `main` branch here a while back which resulted in us rolling back the main branch to an earlier commit and at the time `main` was renamed to `oldmain` as we created the new main branch from the earlier time. This PR is still targeting `oldmain` so in addition to whatever content updates were going to be done for this PR, if there is still any interest as there had been no activity in some months, it also needs to be done to the `main` branch that exists now. My take given how long this has been open and the branch change would be that perhaps this PR is best closed. A new PR using updated content from this, as per the above comments etc., can be opened if there is still interest.

Update: I edited the PR to retarget to main just in case. There is a conflict now. As I mentioned, if there is still interest, it may be better to apply your new content to a updated main and do a new PR.

2025-09-03 14:27 UTC, closed without merging